#!/usr/bin/env bash
CURDIR="$( cd "$( dirname "$0" )" && pwd )"
source $CURDIR/activate
$SPARK_HOME/bin/spark-submit \
    --deploy-mode cluster \
    --master k8s://https://$(minikube ip):8443 \
    $@
